// examples/ecommerce/vue/src/App.vue
<template>
  <div class="app">
    <!-- Header -->
    <header class="header glass">
      <div class="container">
        <div class="header-content">
          <h1 class="logo">
            <span class="logo-icon">✨</span>
            Vue Store
          </h1>
          <div class="header-actions">
            <button class="search-button glass-button">
              <span>🔍</span>
              Search
            </button>
            <button class="wishlist-button glass-button">
              <span>❤️</span>
              <span class="badge">5</span>
            </button>
          </div>
        </div>
      </div>
    </header>

    <!-- Loading State -->
    <div v-if="loading" class="loading">
      <div class="spinner"></div>
      <p>Discovering amazing products...</p>
    </div>

    <!-- Main Content -->
    <template v-else>
      <!-- Featured Deals Banner -->
      <section class="deals-banner">
        <div class="container">
          <h2 class="deals-title">🔥 Flash Deals</h2>
          <div class="deals-grid">
            <div
              v-for="deal in featuredDeals"
              :key="deal.id"
              class="deal-card glass"
            >
              <div class="deal-discount">-{{ Math.round(parseFloat(deal.discount) % 50 || 25) }}%</div>
              <h3 class="deal-title">{{ deal.title }}</h3>
              <button class="deal-button">Shop Now</button>
            </div>
          </div>
        </div>
      </section>

      <!-- Categories -->
      <section class="categories-section">
        <div class="container">
          <h2 class="section-title">Shop by Category</h2>
          <div class="categories-grid">
            <button
              v-for="category in categories"
              :key="category.id"
              class="category-card glass"
              :class="{ active: selectedCategory === category.name }"
              @click="selectedCategory = category.name"
            >
              <div class="category-icon">📦</div>
              <h3 class="category-name">{{ category.name }}</h3>
              <p class="category-count">{{ Math.round(parseFloat(category.productCount) % 100 || 20) }} items</p>
            </button>
            <button
              class="category-card glass"
              :class="{ active: selectedCategory === null }"
              @click="selectedCategory = null"
            >
              <div class="category-icon">🌟</div>
              <h3 class="category-name">All Products</h3>
              <p class="category-count">{{ products.length }} items</p>
            </button>
          </div>
        </div>
      </section>

      <!-- Products -->
      <section class="products-section">
        <div class="container">
          <div class="section-header">
            <h2 class="section-title">
              {{ selectedCategory || 'All Products' }}
            </h2>
            <div class="product-count">
              {{ filteredProducts.length }} products
            </div>
          </div>
          <div class="products-grid">
            <article
              v-for="product in filteredProducts"
              :key="product.id"
              class="product-card glass"
            >
              <div class="product-image-wrapper">
                <img
                  :src="`https://picsum.photos/seed/${product.id}/500/400`"
                  :alt="product.name"
                  class="product-image"
                />
                <button class="wishlist-icon">❤️</button>
                <span v-if="product.inStock" class="stock-badge">
                  ✓ In Stock
                </span>
              </div>
              <div class="product-content">
                <div class="product-meta">
                  <span class="product-category">{{ product.category }}</span>
                  <div class="product-rating">
                    {{ '⭐'.repeat(Math.round(parseFloat(product.rating) % 5 || 4)) }}
                  </div>
                </div>
                <h3 class="product-title">{{ product.name }}</h3>
                <p class="product-description">{{ product.description }}</p>
                <div class="product-footer">
                  <div class="product-price">
                    ${{ parseFloat(product.price).toFixed(2) }}
                  </div>
                  <button class="add-button">
                    <span>+</span>
                    Add
                  </button>
                </div>
              </div>
            </article>
          </div>
        </div>
      </section>
    </template>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <p class="footer-text">
          Built with <span class="heart">💚</span> using
          <strong>Vue 3</strong> & <strong>Symulate SDK</strong>
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { getProducts, getCategories, getFeaturedDeals } from './api'

const products = ref([])
const categories = ref([])
const featuredDeals = ref([])
const loading = ref(true)
const selectedCategory = ref(null)

const filteredProducts = computed(() => {
  if (!selectedCategory.value) return products.value
  return products.value.filter(p => p.category === selectedCategory.value)
})

async function loadData() {
  try {
    loading.value = true
    const [productsData, categoriesData, dealsData] = await Promise.all([
      getProducts(),
      getCategories(),
      getFeaturedDeals(),
    ])
    products.value = productsData
    categories.value = categoriesData
    featuredDeals.value = dealsData
  } catch (error) {
    console.error('Failed to load data:', error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
@import './styles.css';
</style>

// examples/ecommerce/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from './api.service';

interface Product {
  id: string;
  name: string;
  description: string;
  price: string;
  image: string;
  category: string;
  inStock: boolean;
  rating: string;
  reviews: string;
}

interface Category {
  id: string;
  name: string;
  icon: string;
}

interface Review {
  id: string;
  author: string;
  rating: string;
  comment: string;
  date: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  products: Product[] = [];
  categories: Category[] = [];
  reviews: Review[] = [];
  loading = true;
  selectedCategory: string | null = null;
  viewMode: 'grid' | 'list' = 'grid';
  sortBy: 'name' | 'price' | 'rating' = 'name';

  constructor(private apiService: ApiService) {}

  async ngOnInit() {
    await this.loadData();
  }

  async loadData() {
    try {
      this.loading = true;
      const [products, categories, reviews] = await Promise.all([
        this.apiService.getProducts(),
        this.apiService.getCategories(),
        this.apiService.getReviews(),
      ]);
      this.products = products as Product[];
      this.categories = categories as Category[];
      this.reviews = reviews as Review[];
    } catch (error) {
      console.error('Failed to load data:', error);
    } finally {
      this.loading = false;
    }
  }

  get filteredAndSortedProducts(): Product[] {
    let filtered = this.selectedCategory
      ? this.products.filter((p) => p.category === this.selectedCategory)
      : this.products;

    return filtered.sort((a, b) => {
      switch (this.sortBy) {
        case 'price':
          return parseFloat(a.price) - parseFloat(b.price);
        case 'rating':
          return parseFloat(b.rating) - parseFloat(a.rating);
        default:
          return a.name.localeCompare(b.name);
      }
    });
  }

  selectCategory(category: string | null) {
    this.selectedCategory = category;
  }

  getRatingStars(rating: string): string {
    const stars = Math.round(parseFloat(rating) % 5 || 4);
    return '⭐'.repeat(stars);
  }

  getReviewCount(reviews: string): number {
    return Math.round(parseFloat(reviews) % 100 || 50);
  }

  toggleViewMode() {
    this.viewMode = this.viewMode === 'grid' ? 'list' : 'grid';
  }
}

<div class="app">
  <!-- Header -->
  <header class="header glass">
    <div class="container">
      <div class="header-content">
        <h1 class="logo">
          <span class="logo-icon">💎</span>
          <span class="logo-text">
            <span class="logo-main">Angular</span>
            <span class="logo-sub">Luxe</span>
          </span>
        </h1>
        <nav class="nav">
          <button class="nav-button glass-button">
            <span>🏠</span>
            Home
          </button>
          <button class="nav-button glass-button">
            <span>🔍</span>
            Search
          </button>
          <button class="nav-button glass-button">
            <span>👤</span>
            Account
          </button>
          <button class="nav-button glass-button cart-button">
            <span>🛒</span>
            Cart
            <span class="badge">3</span>
          </button>
        </nav>
      </div>
    </div>
  </header>

  <!-- Loading State -->
  <div *ngIf="loading" class="loading">
    <div class="spinner"></div>
    <p>Loading luxury collection...</p>
  </div>

  <!-- Main Content -->
  <ng-container *ngIf="!loading">
    <!-- Hero Reviews Section -->
    <section class="reviews-section glass">
      <div class="container">
        <h2 class="reviews-title">⭐ Customer Reviews</h2>
        <div class="reviews-slider">
          <div *ngFor="let review of reviews" class="review-card">
            <div class="review-rating">
              {{ getRatingStars(review.rating) }}
            </div>
            <p class="review-comment">"{{ review.comment }}"</p>
            <div class="review-author">
              <strong>{{ review.author }}</strong>
              <span class="review-date">{{ review.date.split('T')[0] }}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Categories & Controls -->
    <section class="controls-section">
      <div class="container">
        <div class="controls-header">
          <h2 class="section-title">Shop by Category</h2>
          <div class="controls-actions">
            <select
              (change)="sortBy = $any($event.target).value"
              [value]="sortBy"
              class="sort-select glass-button"
            >
              <option value="name">Sort by Name</option>
              <option value="price">Sort by Price</option>
              <option value="rating">Sort by Rating</option>
            </select>
            <button class="view-toggle glass-button" (click)="toggleViewMode()">
              {{ viewMode === 'grid' ? '☰' : '⊞' }}
            </button>
          </div>
        </div>

        <div class="categories">
          <button
            class="category-btn glass-button"
            [class.active]="selectedCategory === null"
            (click)="selectCategory(null)"
          >
            All Products
          </button>
          <button
            *ngFor="let category of categories"
            class="category-btn glass-button"
            [class.active]="selectedCategory === category.name"
            (click)="selectCategory(category.name)"
          >
            {{ category.name }}
          </button>
        </div>
      </div>
    </section>

    <!-- Products Grid -->
    <main class="container">
      <div class="products-header">
        <h3 class="products-count">
          {{ filteredAndSortedProducts.length }} Products
          <span *ngIf="selectedCategory"> in {{ selectedCategory }}</span>
        </h3>
      </div>

      <div class="products-grid" [class.list-view]="viewMode === 'list'">
        <article
          *ngFor="let product of filteredAndSortedProducts"
          class="product-card glass"
        >
          <div class="product-badge-container">
            <span *ngIf="product.inStock" class="product-badge in-stock">
              ✓ Available
            </span>
            <span *ngIf="!product.inStock" class="product-badge out-of-stock">
              Out of Stock
            </span>
          </div>

          <div class="product-image-container">
            <img
              [src]="'https://picsum.photos/seed/' + product.id + '/600/500'"
              [alt]="product.name"
              class="product-image"
            />
            <button class="quick-view">Quick View</button>
          </div>

          <div class="product-details">
            <span class="product-category">{{ product.category }}</span>
            <h3 class="product-name">{{ product.name }}</h3>
            <p class="product-description">{{ product.description }}</p>

            <div class="product-meta">
              <div class="product-rating-section">
                <span class="rating-stars">{{ getRatingStars(product.rating) }}</span>
                <span class="rating-count">({{ getReviewCount(product.reviews) }})</span>
              </div>
            </div>

            <div class="product-footer">
              <div class="product-price-section">
                <span class="price-label">Price</span>
                <span class="product-price">${{ parseFloat(product.price).toFixed(2) }}</span>
              </div>
              <button class="add-to-cart-btn">
                <span>🛒</span>
                Add to Cart
              </button>
            </div>
          </div>
        </article>
      </div>
    </main>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="footer-content">
          <div class="footer-section">
            <h4>About Angular Luxe</h4>
            <p>Premium e-commerce experience powered by Angular & Symulate SDK</p>
          </div>
          <div class="footer-section">
            <h4>Quick Links</h4>
            <a href="#">Products</a>
            <a href="#">Categories</a>
            <a href="#">About Us</a>
            <a href="#">Contact</a>
          </div>
          <div class="footer-section">
            <h4>Follow Us</h4>
            <p>Stay connected for exclusive deals</p>
          </div>
        </div>
        <div class="footer-bottom">
          <p>Built with Angular 18 & Symulate SDK</p>
        </div>
      </div>
    </footer>
  </ng-container>
</div>
